object_id: 0
object_name: "tomato_soup_can"
plcmnt_volume: [-0.4, 0.29, 0.0, 0.40, 0.78, 0.2]
sdf_volume: [-0.8, -1.0, -0.4, 1.3, 1.0, 1.4]  # relative to robot
object_dictionary : {'ARUCO_MARKER_10': {"path": "../models/",
                                          "dims": [10,10,10],
                                          "footprint": [10,10,10],
                                          "place_height": .9,
                                          "name": "Kethcup"
                                          },
                     "ARUCO_MARKER_11": {"path": "../models/",
                                          "dims": [0.09,0.06,0.15],
                                          "footprint": [10,10,10],
                                          "place_height": 0.9,
                                          "name": "Coffee Powder"
                                          } ,   
                      "ARUCO_MARKER_12": {"path": "../models/",
                                          "dims": [0.055,0.055,.12],
                                          "footprint": [10,10,10],
                                          "place_height": 0.9,
                                          "name": "Mezzo_mix"
                                          },
                      "ARUCO_MARKER_13": {"path": "../models/",
                                          "dims": [0.07,.04,0.1],
                                          "footprint": [70,40,15],
                                          "place_height": 0.9,
                                          "name": "Choco Crisp"
                                          },
                      "ARUCO_MARKER_14": {"path": "../models/",
                                          "dims": [10,10,10],
                                          "footprint": [10,10,10],
                                          "place_height": 0.9,
                                          "name": "Kethcup"
                                          }

                    }